
function getDaysBefore(n: number) { const today = new Date(); today.setDate(today.getDate() - n); return today; }

export const exampleInvoices : any = [
  {
    amount: 100,
    paid: false,
    id: 20,
    date: new Date(),
    pending: false,
  },
  {
    amount: 200,
    paid: getDaysBefore(1),
    id: 19,
    date: getDaysBefore(1),
    pending: false,
  },
  {
    amount: 150,
    paid: false,
    id: 18,
    date: getDaysBefore(2),
    pending: false,
  },
  {
    amount: 300,
    paid: getDaysBefore(3),
    id: 17,
    date: getDaysBefore(3),
    pending: false,
  },
  {
    amount: 250,
    paid: getDaysBefore(4),
    id: 16,
    date: getDaysBefore(4),
    pending: false,
  },
  {
    amount: 180,
    paid: false,
    id: 15,
    date: getDaysBefore(5),
    pending: false,
  },
  {
    amount: 120,
    paid: getDaysBefore(6),
    id: 14,
    date: getDaysBefore(6),
    pending: false,
  },
  {
    amount: 350,
    paid: false,
    id: 13,
    date: getDaysBefore(7),
    pending: false,
  },
  {
    amount: 280,
    paid: getDaysBefore(8),
    id: 12,
    date: getDaysBefore(8),
    pending: false,
  },
  {
    amount: 220,
    paid: false,
    id: 11,
    date: getDaysBefore(9),
    pending: false,
  },
  {
    amount: 400,
    paid: getDaysBefore(10),
    id: 10,
    date: getDaysBefore(10),
    pending: false,
  },
  {
    amount: 320,
    paid: false,
    id: 9,
    date: getDaysBefore(11),
    pending: false,
  },
  {
    amount: 270,
    paid: getDaysBefore(12),
    id: 8,
    date: getDaysBefore(12),
    pending: false,
  },
  {
    amount: 190,
    paid: false,
    id: 7,
    date: getDaysBefore(13),
    pending: false,
  },
  {
    amount: 150,
    paid: getDaysBefore(14),
    id: 6,
    date: getDaysBefore(14),
    pending: false,
  },
  {
    amount: 230,
    paid: false,
    id: 5,
    date: getDaysBefore(15),
    pending: false,
  },
  {
    amount: 380,
    paid: getDaysBefore(16),
    id: 4,
    date: getDaysBefore(16),
    pending: false,
  },
  {
    amount: 290,
    paid: false,
    id: 3,
    date: getDaysBefore(17),
    pending: false,
  },
  {
    amount: 210,
    paid: getDaysBefore(18),
    id: 2,
    date: getDaysBefore(18),
    pending: false,
  },
  {
    amount: 170,
    paid: false,
    id: 1,
    date: getDaysBefore(19),
    pending: false,
  },
];